import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Benjamin Danneville</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center w-screen h-screen bg-gray-900">
          <article className='text-white pr-8'>
            <h1 className='text-2xl font-medium underline'>Benjamin Danneville</h1>
            <h2 className='text-1xl font-light'>Animation and VFX Industry Pipeline TD.</h2>
          </article>
          <aside>
            <div className="w-40 h-40 rounded-full bg-gray-800"></div>
          </aside>
        </div>
      </main>
    </>
  )
}
